name: Interactive Upterm Shell with Tailscale SSH

on:
  workflow_dispatch:
    inputs:
      arch:
        description: 'Runner architecture'
        required: true
        default: 'arm'
        type: choice
        options:
          - arm
          - x86
      clone_armbian:
        description: 'Clone QinCai-rui/armbian-build'
        required: true
        default: true
        type: boolean

jobs:
  persistant-runner:
    runs-on: ${{ inputs.arch == 'arm' && 'ubuntu-24.04-arm' || 'ubuntu-latest' }}

    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y curl jq

      - name: Install and start Tailscale
        env:
          TS_AUTHKEY: ${{ secrets.TS_AUTH_KEY }}
        run: |
          if [ -z "$TS_AUTHKEY" ]; then
            echo "ERROR: secrets.TS_AUTH_KEY is empty or not set"
            exit 1
          fi

          curl -fsSL https://tailscale.com/install.sh | sh
          sudo tailscale up --auth-key="$TS_AUTHKEY"
          sudo tailscale set --ssh

      - name: Install Upterm
        run: |
          URL=$(curl -s https://api.github.com/repos/owenthereal/upterm/releases/latest \
            | jq -r '.assets[].browser_download_url' \
            | grep 'upterm_linux_arm64.deb')

          echo "Downloading: $URL"

          curl -L "$URL" -o upterm.deb
          sudo apt install -y ./upterm.deb

      - name: Check
        run: |
          uname -m
          upterm version
          echo "My Tailscale IP is: $(tailscale ip | sed -n 1p)"

      - name: Generate Upterm key
        run: |
          mkdir -p ~/.upterm
          ssh-keygen -t ed25519 -N "" -f ~/.upterm/id_ed25519
          cat ~/.upterm/id_ed25519.pub

      - name: Checkout Armbian build
        if: ${{ inputs.clone_armbian }}
        uses: actions/checkout@v4
        with:
          repository: QinCai-rui/armbian-build
          path: armbian-build
          token: ${{ secrets.GH_TOKEN }}
    
      - name: Start Upterm
        run: |
          upterm host \
            --server wss://upterm.qincai.xyz \
            --private-key ~/.upterm/id_ed25519 \
            --accept \
            --github-user QinCai-rui \
            --skip-host-key-check
